package com.demo.model.mdao;

import com.demo.pojo.Beputxq;
import java.util.List;

public interface BeputxqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beputxq
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bexqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beputxq
     *
     * @mbg.generated
     */
    int insert(Beputxq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beputxq
     *
     * @mbg.generated
     */
    Beputxq selectByPrimaryKey(Integer bexqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beputxq
     *
     * @mbg.generated
     */
    List<Beputxq> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beputxq
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Beputxq record);
}