package com.demo.model.mdao;

import com.demo.pojo.Beput;
import java.util.List;

public interface BeputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beput
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer beid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beput
     *
     * @mbg.generated
     */
    int insert(Beput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beput
     *
     * @mbg.generated
     */
    Beput selectByPrimaryKey(Integer beid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beput
     *
     * @mbg.generated
     */
    List<Beput> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beput
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Beput record);
}