package com.demo.model.mdao;

import com.demo.pojo.Checks;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface ChecksMapper {
    /*
     * @Author xieyukun
     * @Description selectAndchecksxq
     * @Date 9:35 2020/12/24
     * @param [cheid]
     * @return java.util.List<com.demo.pojo.Checks>
    */
    List<Checks> selectAndchecksxq(Integer cheid);
    /* 查询盘点和产品
     * @Author xieyukun
     * @Description selectAndproduct
     * @Date 9:14 2020/12/23
     * @param [cheid, lname, ltiaoma, date1, date2]
     * @return java.util.List<com.demo.pojo.Checks>
    */
    List<Checks> selectAndproduct(Integer cheid,String lname,String ltiaoma,String date1, String date2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cheid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    int insert(Checks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    Checks selectByPrimaryKey(Integer cheid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    List<Checks> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Checks record);
}