package com.demo.model.mdao;

import com.demo.pojo.Checks;
import java.util.List;

public interface ChecksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cheid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    int insert(Checks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    Checks selectByPrimaryKey(Integer cheid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    List<Checks> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checks
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Checks record);
}