package com.demo.model.mdao;

import com.demo.pojo.Checkxq;
import java.util.List;

public interface CheckxqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkxq
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer chexqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkxq
     *
     * @mbg.generated
     */
    int insert(Checkxq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkxq
     *
     * @mbg.generated
     */
    Checkxq selectByPrimaryKey(Integer chexqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkxq
     *
     * @mbg.generated
     */
    List<Checkxq> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checkxq
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Checkxq record);
}