package com.demo.model.mdao;

import com.demo.pojo.Cprandcom;
import java.util.List;

public interface CprandcomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprandcom
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cproid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprandcom
     *
     * @mbg.generated
     */
    int insert(Cprandcom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprandcom
     *
     * @mbg.generated
     */
    Cprandcom selectByPrimaryKey(Integer cproid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprandcom
     *
     * @mbg.generated
     */
    List<Cprandcom> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cprandcom
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cprandcom record);
}