package com.demo.model.mdao;

import com.demo.pojo.Customer;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cid3);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    Customer selectByPrimaryKey(Integer cid3);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    List<Customer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Customer record);

    /*
     * @Author 周子豪
     * @Description 10:13
     * @Date  2020/12/23
     * @param [cid]
     * @return com.demo.pojo.Customer
     * 根据客户id查询
    */
    Customer selectByCid(Integer cid);

    /*
     * @Author 周子豪
     * @Description 21:04
     * @Date  2020/12/23
     * @param [cname, password]
     * @return com.demo.pojo.Customer
     * 登录
    */
    Customer dengLu(@Param("cname") String cname, @Param("password") String password);
}