package com.demo.model.mdao;

import com.demo.pojo.Inventory;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface InventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int insert(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    Inventory selectByPrimaryKey(Integer inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    List<Inventory> selectAll();
    /*
     * @Author xieyukun
     * @Description selectAndproductAll
     * @Date 21:37 2020/12/21
     * @param []
     * @return java.util.List<com.demo.pojo.Inventory>
    */
    List<Inventory> selectAndproductAll(String lname,String ltiaoma);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Inventory record);
}