package com.demo.model.mdao;

import com.demo.pojo.Inventory;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface InventoryMapper {
    /*
     * @Author xieyukun
     * @Description updateinentity
     * @Date 15:44 2020/12/24
     * @param [inentity, inusable, lid]
     * 库存盘点重置单品库存
     *  @return java.lang.Integer
    */
    Integer updateinentity(Integer inentity,Integer inusable,Integer lid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int insert(Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    Inventory selectByPrimaryKey(Integer inid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    List<Inventory> selectAll();
    /*
     * @Author xieyukun
     * @Description selectAndproductAll
     * @Date 21:37 2020/12/21
     * @param []
     * @return java.util.List<com.demo.pojo.Inventory>
    */
    List<Inventory> selectAndproductAll(String lname,String ltiaoma);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Inventory record);
    /*
     * @Author xieyukun
     * @Description updatekucun
     * @Date 20:58 2020/12/23
     * @param [inentity, inusable, lid]
     * @return java.lang.Integer
     * 入库加库存
    */
    Integer updatekucun(Integer inentity,Integer inusable ,Integer lid);
    /*
     * @Author xieyukun
     * @Description updatemaxcount
     * @Date 10:19 2020/12/24
     * @param [maxcount, inid]
     * @return java.lang.Integer
     * 设置超卖库存
    */
    Integer updatemaxcount(Integer maxcount,Integer inid);
    /*
     * @Author xieyukun
     * @Description updatekucunjian
     * @Date 10:20 2020/12/24
     * @param [inentity, inusable, lid]
     * @return java.lang.Integer
     * 出库减库存
    */
    Integer updatekucunjian(Integer inentity,Integer inusable,Integer lid);
}