package com.demo.model.mdao;

import com.demo.pojo.*;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.Date;
import java.util.List;
@Repository
@Mapper
public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    Orders selectByPrimaryKey(Integer oId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *查询所有订单
     * @mbg.generated
     */
    List<Orders> selectAll(@Param("ortype") String ortype, @Param("orsip") String orsip, @Param("pay") String pay);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Orders record);

    /*
    * 查询订单详情商品和图片
    * */
    List<picvo> selectcompic(Integer oId);

    /*根据编号查询订单*/
    ordervo seorder(Integer oId);

    /*根据订单编号修改订单状态*/
    Integer uporder(@Param("or")Orders o);

    /*查询未发货订单*/
    List<Orders> orderstwo( @Param("orsip") String orsip, @Param("pay") String pay);
}