package com.demo.model.mdao;

import com.demo.pojo.Outandinput;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface OutandinputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outandinput
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer outinid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outandinput
     *
     * @mbg.generated
     */
    int insert(Outandinput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outandinput
     *
     * @mbg.generated
     */
    Outandinput selectByPrimaryKey(Integer outinid);
    /*
     * @Author xieyukun
     * @Description selectAll
     * @Date 15:26 2020/12/22
     * @param [lname, ltiaoma, yewuid, outinid, outinclass, date1, date2]
     * @return java.util.List<com.demo.pojo.Outandinput>
    */
    List<Outandinput> selectAll(String lname,String ltiaoma,Integer yewuid,Integer outinid,String outinclass,String date1,String date2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outandinput
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Outandinput record);
}