package com.demo.model.mdao;

import com.demo.pojo.Outandinput;
import java.util.List;

public interface OutandinputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outandinput
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer outinid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outandinput
     *
     * @mbg.generated
     */
    int insert(Outandinput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outandinput
     *
     * @mbg.generated
     */
    Outandinput selectByPrimaryKey(Integer outinid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outandinput
     *
     * @mbg.generated
     */
    List<Outandinput> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outandinput
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Outandinput record);
}