package com.demo.model.mdao;

import com.demo.pojo.Output;
import java.util.List;

public interface OutputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer outid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    int insert(Output record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    Output selectByPrimaryKey(Integer outid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    List<Output> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Output record);
}