package com.demo.model.mdao;

import com.demo.pojo.Output;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface OutputMapper {
    /*
     * @Author xieyukun
     * @Description selectoutxq
     * @Date 15:15 2020/12/23
     * @param [outid]
     * @return java.util.List<com.demo.pojo.Output>
    */
    List<Output> selectoutxq(Integer outid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer outid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    int insert(Output record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    Output selectByPrimaryKey(Integer outid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    List<Output> selectAll(String outclass,Integer outid,Integer yewuid,String date1,String date2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table output
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Output record);
}