package com.demo.model.mdao;

import com.demo.pojo.Outputxq;
import java.util.List;

public interface OutputxqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputxq
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer outxqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputxq
     *
     * @mbg.generated
     */
    int insert(Outputxq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputxq
     *
     * @mbg.generated
     */
    Outputxq selectByPrimaryKey(Integer outxqid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputxq
     *
     * @mbg.generated
     */
    List<Outputxq> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table outputxq
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Outputxq record);
}