package com.demo.model.mdao;

import com.demo.pojo.SpCommoditycategory;
import java.util.List;

public interface SpCommoditycategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditycategory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ccyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditycategory
     *
     * @mbg.generated
     */
    int insert(SpCommoditycategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditycategory
     *
     * @mbg.generated
     */
    SpCommoditycategory selectByPrimaryKey(Integer ccyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditycategory
     *
     * @mbg.generated
     */
    List<SpCommoditycategory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditycategory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpCommoditycategory record);
}