package com.demo.model.mdao;

import com.demo.pojo.SpCommoditytopro;
import java.util.List;

public interface SpCommoditytoproMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditytopro
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ctpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditytopro
     *
     * @mbg.generated
     */
    int insert(SpCommoditytopro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditytopro
     *
     * @mbg.generated
     */
    SpCommoditytopro selectByPrimaryKey(Integer ctpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditytopro
     *
     * @mbg.generated
     */
    List<SpCommoditytopro> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commoditytopro
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpCommoditytopro record);
}