package com.demo.model.mdao;

import com.demo.pojo.SpCommodityproperty;
import java.util.List;

public interface SpCommoditypropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commodityproperty
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cpyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commodityproperty
     *
     * @mbg.generated
     */
    int insert(SpCommodityproperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commodityproperty
     *
     * @mbg.generated
     */
    SpCommodityproperty selectByPrimaryKey(Integer cpyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commodityproperty
     *
     * @mbg.generated
     */
    List<SpCommodityproperty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_commodityproperty
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpCommodityproperty record);
}