package com.demo.model.mdao;

import com.demo.pojo.SpPicturesort;
import java.util.List;

public interface SpPicturesortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturesort
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pisid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturesort
     *
     * @mbg.generated
     */
    int insert(SpPicturesort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturesort
     *
     * @mbg.generated
     */
    SpPicturesort selectByPrimaryKey(Integer pisid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturesort
     *
     * @mbg.generated
     */
    List<SpPicturesort> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturesort
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpPicturesort record);
}