package com.demo.model.mdao;

import com.demo.pojo.SpPicturetopro;
import java.util.List;

public interface SpPicturetoproMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturetopro
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer ptpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturetopro
     *
     * @mbg.generated
     */
    int insert(SpPicturetopro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturetopro
     *
     * @mbg.generated
     */
    SpPicturetopro selectByPrimaryKey(Integer ptpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturetopro
     *
     * @mbg.generated
     */
    List<SpPicturetopro> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturetopro
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpPicturetopro record);
}