package com.demo.model.mdao;

import com.demo.pojo.SpPicturetopro;
import com.demo.pojo.SpProduct;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface SpPicturetoproMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_picturetopro
     *
     * @mbg.generated
     */
    int insertInfo(@Param("s") SpPicturetopro topro);


}