package com.demo.model.mdao;

import com.demo.pojo.SpProductsort;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface SpProductsortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cid2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    void insert(@Param("r") SpProductsort r);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    SpProductsort selectByPrimaryKey(Integer cid2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    List<SpProductsort> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpProductsort record);

    List<SpProductsort> selectFu();

    List<SpProductsort> selectByid(Integer id);
}