package com.demo.model.mdao;

import com.demo.pojo.SpProductsort;
import java.util.List;

public interface SpProductsortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cid2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    int insert(SpProductsort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    SpProductsort selectByPrimaryKey(Integer cid2);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    List<SpProductsort> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_productsort
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpProductsort record);
}