package com.demo.model.mdao;

import com.demo.pojo.SpProduct;
import java.util.List;

public interface SpProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    int insert(SpProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    SpProduct selectByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    List<SpProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpProduct record);
}