package com.demo.model.mdao;

import com.demo.pojo.SpProduct;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface SpProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    int insert(@Param("p") SpProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    SpProduct selectByPrimaryKey(Integer lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    List<SpProduct> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sp_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SpProduct record);
}