package com.demo.model.mdao;

import com.demo.pojo.Supplier;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface SupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer suid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    int insert(Supplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    Supplier selectByPrimaryKey(Integer suid);
    /*
     * @Author xieyukun
     * @Description selectNewBeput
     * @Date 20:18 2020/12/23
     * @param []
     * @return java.util.List<com.demo.pojo.Supplier>
    */
    List<Supplier> selectNewBeput();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    List<Supplier> selectAll(String suname,String sulxr,String sulxrphone,Integer suid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Supplier record);
}