spring:
  datasource:
    url: jdbc:mysql://47.101.141.162:3306/ooa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: jd
    password: zktr123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat
  jpa:
    show-sql: true

server:
  port: 8881

mybatis:
  type-aliases-package: com.study.pojo
  mapper-locations: classpath:mapper/*Mapper.xml

  logging:
    level:
      com:
        study:
          model:
            mdao:debug

