mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.demo.pojo
spring:
  datasource:
    username: jd
    password: "zktr123456"
    url: jdbc:mysql://47.101.141.162:3306/jindun?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filter: stat
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
server:
  port: 8086
