server:
  port: 8087

mybatis:
  #扫描Mapper的接口文件
  #指定mapper映射文件（xml文件）所在的位置
  mapper-locations: classpath*:mapper/*Mapper.xml
  #指定实体类的别称所通用的包名
  type-aliases-package: com.crm.pojo
spring:
  datasource:
    username: root
    password: "!Mysql2020"
    url: jdbc:mysql://47.93.57.70:3306/xyk?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com:
      crm:
        model:
          mdao: debug
